### PR TITLE
Proposal for unified agenda/note file for 2020

### PR DESCRIPTION
**Pull request by valgrimm**
I propose storing the meeting agendas and notes for 2020 in one file for ease of access. This is imitating an approach used in many meetings in the department where I work.

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your PR! I think it would be easier if the agenda and notes were was available through a collaboration document on Dropbox Paper or HackMD, and then we link to it from the GitHub repo. We should also keep all the minutes in seperate documents in `minutes/` so that they are easy to link to.

**Comment by valgrimm** [comment]
Thank you for your prompt and helpful comment.  The thought behind this proposal was to minimize administration by keeping information in one place. What are some benefits of storing the notes on Dropbox Paper or HackMD instead of Github, and separating the documents?

**Comment by XAMPPRocky** [comment]
> What are some benefits of storing the notes on Dropbox Paper or HackMD instead of Github

Well the main motivation is that multiple people can edit and work on a Paper or HackMD document, which makes it easy for multiple people to take notes during the meeting. Another important aspect is that you can start writing in the document as soon as you click the link, reducing cognitive overhead.

Sorry if it was unclear I didn't mean that it would stored solely in one or other, I would expect that after a meeting, the minutes are added to GitHub. The reasoning for storing separated documents is that it's easy to see everything that happened in the meeting without feeling lost in a big single document. It's also easy to find with GitHub's UI.

It's not that we're trying to store documents in one place or another, it's more that we're taking advantages of different services for different needs. In the meeting we want something that allows us to collaborate the easiest, which has been Paper/HackMD so far. After the meeting we want a place that's easily searchable and visible to ourselves and non members.

On the agenda document itself I would like if there was a "Agenda Backlog" or something that is essentially just a list of the action items we've mentioned in the past, that we haven't done anything with yet, so that we remember to follow up with them.

**Comment by valgrimm** [comment]
Thanks for this. Ok, so it sounds like a good process should be something like:
Create an agenda/notes doc for meeting in HackMD (I'm going to pick this as I've met weird activity limits for free accounts on Dropbox)
Copy the notes and agenda to Github after the meeting. 
I'll close this pull request and create another "meeting procedure" one to confirm the agenda/notes process for future reference. Of course that can be modified too. But then there's a clear agreed-upon approach. Maybe I'm creating too much overhead, as it is already understood to create the blog post and such. But yeah . . . . if it is helpful, then good. If not, one can always close the pull request.

**Comment by valgrimm** [comment]
actually, not going to create a proposal, everyone knows this, I just needed to discover it.

**Comment by XAMPPRocky** [comment]
Well we do we at least need a stable document in either HackMD (I think this is preferable) or Dropbox Paper, and to link to that from the README in the repo, if you wanted to take that on you're more than welcome to, otherwise I'll do it before/after our meeting.

**Comment by valgrimm** [comment]
Ah ok @XAMPPRocky sounds good to me. Happy to use the HackMD I created for the meeting today for this purpose. I'll modify the readme. https://hackmd.io/ATj1rZJaRimaIfIWfAOYfQ?edit

**Pull request closed without merging**
