### PR TITLE
Proposed charter update

### PR DESCRIPTION
**Pull request by valgrimm**
Hi @XAMPPRocky I've updated the charter with the notes in the agenda doc from last meeting. These notes are also in the minutes from last meeting. I'm going to clean out the agenda doc. Happy to revise.

### CODE REVIEW

**Comment by nrc** [comment]
Not directly related to the PR, IMO it is better for a group's charter to be a mostly static document, something like a vision and constitution for the group. Current status and similar are best kept as issues, a project, or a separate, more dynamic document. Obviously its for the WG to decide, hope it is OK to add my 2c.

**Comment by Manishearth** [comment]
Yeah, i think some parts of the charter should be changed: the group has changed over time, and [the "out of scope" section](https://github.com/rust-lang/wg-governance/blob/master/CHARTER.md#out-of-scope) has a rather pointed tone. But I don't think it should be a live document tracking our current initiatives.

**Comment by BatmanAoD** [comment]
I think it might be reasonable to keep a live "projects in flight" document, although the maintenance burden may outweigh any benefits. If we do maintain such a document, though, it should definitely be separate from the charter.

**Comment by XAMPPRocky** [comment]
Yeah i agree that the the charter should mostly be a static document. We do now have a live version of these proposed goals as a project board I just made over the weekend. https://github.com/rust-lang/wg-governance/projects/5

**Comment by BatmanAoD** [comment]
That project board is very nice!

**Comment by valgrimm** [comment]
I agree @XAMPPRocky , super project board! I'm going to change this PR, because it sounds like what @Manishearth  said is a good point. But first I want to make sure what to change . . . Listing in-flight things doesn't need to be here, but what *does* need to change?
So far I have:
1) "In scope" is too pointed

Anything else I should fix? When I know what I'll remove the "in-flight" info from the charter. 

I totally see the point about it not including "in-flight" work, it is just that the "future entity" section made me think it might be.
Also, from project management classes/experience, I have an unconscious bias toward something called a charter being "a thing that defines the expectations/deliverables for a project", when this isn't a project team with a definitive end state and so that doesn't apply. That said, even project charters generally don't change mid-stream.

**Comment by XAMPPRocky** [comment]
I would like to revisit the charter either at the end of year or once we've felt we've met enough of the "Domain working groups" and "Staged RFCs" goals (whichever's first). I feel that we are still working towards those goals though how we are achieving them has changed a lot, so I would prefer to start a refresh of the charter with new goals. That would also be a good time to also switch terminology for this group from working group.

**Comment by valgrimm** [comment]
Ok, then I shall go ahead and close this PR and set a calendar alert to remind me to followup. Thank you!

**Pull request closed without merging**
